version: '3'
services:
  airflow:
    build:
      dockerfile: Dockerfile.airflow
    restart: always
    environment:
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
    ports:
      - "8090:8080"
    command: ["airflow", "standalone"]
    networks:
      - mlnet

  ml-service:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5102:5102"
    networks:
      - mlnet

networks:
  mlnet:
    driver: bridge